vscode:
  extensions:
    - ritwickdey.live-sass@3.0.0:x2c+sCJm+QmH2qn2h1X9Zw==
    - gencer.html-slim-scss-css-class-completion@1.7.5:iSvfKBHJrWBs7kB7jkDDAw==
    - codelios.dartsass@0.6.8:Pto2BOoEwHCO/GYSYUuu8w==